type OwnershipTransferred @entity(immutable: true) {
  id: Bytes!
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type VaultFromProposalPermissionUpgradeRequested @entity(immutable: true) {
  id: Bytes!
  proposalId: Bytes! # bytes32
  user: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type VaultFromProposalRegisteredOnForeignChain @entity(immutable: true) {
  id: Bytes!
  proposalId: Bytes! # bytes32
  tokenContract: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
